import type {
  AudienceSegment,
  Brand,
  BrandKit,
  BrandPatch,
  LearningImpact,
  NewBrandInput,
  Platform,
  PostArt,
  PostFormat,
  PostStatus,
  Role,
} from "@social-agent/shared";

// Types the API shares live in @social-agent/shared. This file holds only what the web adds on top.

/** A brand workspace as the mock serves it: the API's Brand without the fields the UI does not read yet. */
export type Client = Omit<Brand, "createdBy" | "status" | "business" | "intake" | "intakeApprovedAt">;

export interface ContentPillar {
  id: string;
  name: string;
  description: string;
  /** Share of the content mix, 0-100. */
  share: number;
}

export interface Learning {
  id: string;
  insight: string;
  evidence: string;
  impact: LearningImpact;
}

export interface Strategy {
  clientId: string;
  version: number;
  generatedAt: string;
  goal: string;
  pillars: ContentPillar[];
  cadence: { platform: Platform; perWeek: number; bestTimes: string[] }[];
  audience: AudienceSegment[];
  learnings: Learning[];
}

export interface PostMetrics {
  reach: number;
  likes: number;
  comments: number;
  saves: number;
  shares: number;
}

export interface Post {
  id: string;
  clientId: string;
  platform: Platform;
  format: PostFormat;
  pillarId: string;
  /** Short on-image headline. */
  hook: string;
  caption: string;
  hashtags: string[];
  status: PostStatus;
  scheduledFor: string | null;
  publishedAt: string | null;
  /**
   * The post's real image, once there is one: uploaded by the client, or (later)
   * generated by the agent. While null, the UI draws artwork from the brand colours.
   */
  mediaUrl?: string | null;
  art: PostArt;
  durationSec?: number;
  /** Why the agent made this post. Shown to the approver. */
  aiNote: string;
  metrics?: PostMetrics;
}

export interface AnalyticsPoint {
  date: string;
  reach: number;
  engagement: number;
  followers: number;
}

export interface Analytics {
  clientId: string;
  series: AnalyticsPoint[];
  byFormat: { format: PostFormat; engagementRate: number; posts: number }[];
  byPillar: { pillarId: string; name: string; reach: number }[];
}

export interface BrandScanStep {
  id: string;
  label: string;
  detail: string;
}

export type NewClientInput = Pick<NewBrandInput, "name" | "url" | "industry" | "brand" | "platforms">;

/** The parts of a client its owner can change in Settings. */
export type ClientPatch = Omit<BrandPatch, "business">;

/** The signed-in person, resolved on the server from Clerk. */
export interface Viewer {
  id: string;
  role: Role;
  name: string;
  email: string;
}

/** The mock scan's result. The API's ScanResult has optional name and industry; this comes off with the mock. */
export interface ScanResult {
  name: string;
  industry: string;
  brand: BrandKit;
}

/** A brand scan job: started once, then polled until it is done. */
export interface Scan {
  id: string;
  url: string;
  /** Index of the step in progress; equals the step count when done. */
  step: number;
  status: "running" | "done";
  result: ScanResult | null;
}

export interface PostPatch {
  status?: PostStatus;
  caption?: string;
  hook?: string;
  hashtags?: string[];
  /** A data URL in the mock. The real API takes an upload and returns a hosted URL. */
  mediaUrl?: string | null;
  scheduledFor?: string | null;
}
