export type Platform = "instagram" | "facebook" | "linkedin" | "tiktok";
export type PostFormat = "image" | "carousel" | "reel" | "story";
export type PostStatus =
  | "draft"
  | "in_review"
  | "approved"
  | "scheduled"
  | "published"
  | "rejected";

/** Where a client currently sits in the agent loop. */
export type LoopStage =
  | "onboarding"
  | "strategy"
  | "content"
  | "approval"
  | "publishing"
  | "learning";

export interface BrandColor {
  name: string;
  hex: string;
}

export interface BrandKit {
  tagline: string;
  summary: string;
  audience: string;
  voice: string[];
  colors: BrandColor[];
  fonts: { heading: string; body: string };
}

/** A social profile the agent is allowed to publish to. */
export interface SocialAccount {
  platform: Platform;
  handle: string;
  /** "expired" means the network revoked access and the owner has to reconnect. */
  status: "connected" | "expired";
  connectedAt: string;
}

export interface ClientPreferences {
  /** IANA name, e.g. "Asia/Kolkata". Publish times are shown and scheduled in it. */
  timezone: string;
  /** Email the owner when posts are waiting for approval. */
  approvalEmails: boolean;
}

export interface Client {
  id: string;
  /** The user who owns this client. Admins can see every client regardless. */
  ownerId: string;
  name: string;
  url: string;
  industry: string;
  /** Primary brand colour. The workspace chrome tints to this. */
  accent: string;
  stage: LoopStage;
  brand: BrandKit;
  /** Where the strategy plans to post. */
  platforms: Platform[];
  /** Which of those are actually connected. A platform without an account can't publish. */
  accounts: SocialAccount[];
  preferences: ClientPreferences;
  createdAt: string;
  stats: {
    followers: number;
    followersDelta: number;
    engagementRate: number;
    engagementDelta: number;
    scheduled: number;
    pendingApprovals: number;
  };
}

export interface ContentPillar {
  id: string;
  name: string;
  description: string;
  /** Share of the content mix, 0-100. */
  share: number;
}

export interface Learning {
  id: string;
  insight: string;
  evidence: string;
  impact: "up" | "down" | "neutral";
}

export interface Strategy {
  clientId: string;
  version: number;
  generatedAt: string;
  goal: string;
  pillars: ContentPillar[];
  cadence: { platform: Platform; perWeek: number; bestTimes: string[] }[];
  audience: { segment: string; note: string }[];
  learnings: Learning[];
}

export interface PostMetrics {
  reach: number;
  likes: number;
  comments: number;
  saves: number;
  shares: number;
}

export interface Post {
  id: string;
  clientId: string;
  platform: Platform;
  format: PostFormat;
  pillarId: string;
  /** Short on-image headline. */
  hook: string;
  caption: string;
  hashtags: string[];
  status: PostStatus;
  scheduledFor: string | null;
  publishedAt: string | null;
  /**
   * The post's real image, once there is one: uploaded by the client, or (later)
   * generated by the agent. While null, the UI draws artwork from the brand colours.
   */
  mediaUrl?: string | null;
  /** Procedural artwork seed: layout variant + index into brand colours. */
  art: { variant: number; colorIndex: number };
  durationSec?: number;
  /** Why the agent made this post. Shown to the approver. */
  aiNote: string;
  metrics?: PostMetrics;
}

export interface AnalyticsPoint {
  date: string;
  reach: number;
  engagement: number;
  followers: number;
}

export interface Analytics {
  clientId: string;
  series: AnalyticsPoint[];
  byFormat: { format: PostFormat; engagementRate: number; posts: number }[];
  byPillar: { pillarId: string; name: string; reach: number }[];
}

export interface BrandScanStep {
  id: string;
  label: string;
  detail: string;
}

export interface NewClientInput {
  name: string;
  url: string;
  industry: string;
  brand: BrandKit;
  platforms: Platform[];
}

/** The parts of a client its owner can change in Settings. */
export interface ClientPatch {
  name?: string;
  industry?: string;
  brand?: BrandKit;
  platforms?: Platform[];
  preferences?: ClientPreferences;
}

export type Role = "admin" | "client";

/** The signed-in person, resolved on the server from Clerk. */
export interface Viewer {
  id: string;
  role: Role;
  name: string;
  email: string;
}

export interface ScanResult {
  name: string;
  industry: string;
  brand: BrandKit;
}

/** A brand scan job: started once, then polled until it is done. */
export interface Scan {
  id: string;
  url: string;
  /** Index of the step in progress; equals the step count when done. */
  step: number;
  status: "running" | "done";
  result: ScanResult | null;
}

export interface PostPatch {
  status?: PostStatus;
  caption?: string;
  hook?: string;
  hashtags?: string[];
  /** A data URL in the mock. The real API takes an upload and returns a hosted URL. */
  mediaUrl?: string | null;
  scheduledFor?: string | null;
}
