// Fails when the API's routes and the committed OpenAPI document disagree.
// Run: pnpm --filter api run openapi:check
//
// Routes come from ./routes.cjs (it reads the Express routers under src/); operations come
// from openapi/openapi.json, generated by scripts/openapi.ts from src/openapi/operations.ts.
const fs = require("fs");
const path = require("path");
const { listRoutes } = require("./routes.cjs");

const docPath = path.join(__dirname, "openapi.json");
const doc = JSON.parse(fs.readFileSync(docPath, "utf8"));

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"];

/** OpenAPI's "{id}" path params back to Express's ":id", to compare against a route's path. */
const toExpressPath = (openApiPath) => openApiPath.replace(/\{([^}]+)\}/g, ":$1");

function operationsOf(document) {
    const found = [];
    for (const [openApiPath, methods] of Object.entries(document.paths ?? {})) {
        for (const method of HTTP_METHODS) {
            if (methods[method]) found.push({ method: method.toUpperCase(), path: toExpressPath(openApiPath) });
        }
    }
    return found;
}

const same = (a, b) => a.method === b.method && a.path === b.path;

const routes = listRoutes();
const operations = operationsOf(doc);

const routesWithoutOperation = routes.filter((route) => !operations.some((operation) => same(route, operation)));
const operationsWithoutRoute = operations.filter((operation) => !routes.some((route) => same(route, operation)));

console.log(`${routes.length} routes in the API, ${operations.length} operations in openapi.json.`);

if (routesWithoutOperation.length > 0 || operationsWithoutRoute.length > 0) {
    if (routesWithoutOperation.length > 0) {
        console.error("\nRoutes with no operation in src/openapi/operations.ts:");
        for (const route of routesWithoutOperation) console.error(`  ${route.method} ${route.path}`);
    }
    if (operationsWithoutRoute.length > 0) {
        console.error("\nOperations with no matching route:");
        for (const operation of operationsWithoutRoute) console.error(`  ${operation.method} ${operation.path}`);
    }
    console.error("\nFix src/openapi/operations.ts, then run: pnpm --filter api run openapi");
    process.exit(1);
}

console.log("Every route has an operation, and every operation has a route.");
