// Fails when the API's real Express routes and the generated OpenAPI document disagree.
// Run: pnpm --filter api run openapi:check
//
// Routes come from scripts/routes.ts (it reads the routers under src/); operations come from
// openapi/openapi.json, generated by scripts/openapi.ts out of src/openapi/operations.ts. The two
// are derived from different sources on purpose: that is what makes this a check and not a tautology.
import fs from "node:fs";
import path from "node:path";
import { listRoutes, type Route } from "./routes";

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const;

const docPath = path.join(import.meta.dirname, "..", "openapi", "openapi.json");

/** OpenAPI's `{id}` path params back to Express's `:id`, so the two lists can be compared. */
const toExpressPath = (openApiPath: string): string => openApiPath.replace(/\{([^}]+)\}/g, ":$1");

function operationsOf(document: { paths?: Record<string, Record<string, unknown>> }): Route[] {
    const found: Route[] = [];
    for (const [openApiPath, methods] of Object.entries(document.paths ?? {})) {
        for (const method of HTTP_METHODS) {
            if (methods[method]) found.push({ method: method.toUpperCase(), path: toExpressPath(openApiPath) });
        }
    }
    return found;
}

const same = (a: Route, b: Route): boolean => a.method === b.method && a.path === b.path;

const routes = listRoutes();
const operations = operationsOf(JSON.parse(fs.readFileSync(docPath, "utf8")));

const routesWithoutOperation = routes.filter((route) => !operations.some((operation) => same(route, operation)));
const operationsWithoutRoute = operations.filter((operation) => !routes.some((route) => same(route, operation)));

console.log(`${routes.length} routes in the API, ${operations.length} operations in openapi.json.`);

if (routesWithoutOperation.length > 0 || operationsWithoutRoute.length > 0) {
    if (routesWithoutOperation.length > 0) {
        console.error("\nRoutes with no operation in src/openapi/operations.ts:");
        for (const route of routesWithoutOperation) console.error(`  ${route.method} ${route.path}`);
    }
    if (operationsWithoutRoute.length > 0) {
        console.error("\nOperations with no matching route:");
        for (const operation of operationsWithoutRoute) console.error(`  ${operation.method} ${operation.path}`);
    }
    console.error("\nFix src/openapi/operations.ts, then run: pnpm --filter api run openapi");
    process.exit(1);
}

console.log("Every route has an operation, and every operation has a route.");
